baseURL: "https://nehalh.github.io/portfolio/"
languageCode: en-us
title: Nehal Hosalikar
theme: PaperMod
googleAnalytics: "G-QTYSD4HXKK"

menu:
  main:
    - identifier: home
      name: Profile
      url: /
      weight: 10
    # - identifier: blog
    #   name: Blog
    #   url: /blog/comingsoon
    #   weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: certifications
      name: Certifications
      url: /certifications
      weight: 40
    # - identifier: experience
    #   name: Experience
    #   url: /experience
    #   weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: 
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production
  title: Nehal Hosalikar
  description: "Portfolio website by Nehal Hosalikar"
  keywords: [Portfolio, Nehal, Hosalikar, Sahyadri, Deloitte, Nehal Hosalikar]
  author: Nehal Hosalikar

  # Home Page
  profileMode:
    enabled: true
    title: "Nehal Hosalikar"
    subtitle: Product Engineer at [**Deloitte.**](https://www.deloitte.com/global/en.html)

    imageUrl: "home/profile-img.jpeg"
    imageWidth: 300
    imageHeight: 300
    buttons:
      - name: About
        url: about/about
      - name: Resume
        url: "https://drive.google.com/file/d/1cCrmL0Lsp93JdPw1wfBm6HfUWR9mLfwm/view?usp=sharing"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:nhosalikar@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/nehal-hosalikar-35535a204"
    - name: "github"
      url: "https://github.com/NehalH"
    #- name: "youtube"
    #  url: ""
    #- name: "cv"
    #  url: "https://drive.google.com/file/d/1Mp3cypZ_ioFDl_Nh0uepbfxLjEdJoI1c/view?usp=drive_link"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
